### ISSUE TITLE
Sidebar Scrolling

### ISSUE THREAD

**Issue by adamdoe** [marketingincolor/egw-site-themes#106]
@eddt ,

This isn't a confirmed issue or feature request yet. However, I think its only a matter of time before it gets brought up. On pages that have a sidebar it might be nice to have the sidebar follow the user down the page without clashing into the header or footer. I think the real benefit and sell of this feature is that ads will always be in the users viewport.

**Comment by eddt** [comment]
@adamdoe - This is GOOD thinking, bud! This is probably something that John would get pretty excited about, if we could get it to work! I've put it in the Phase 3 project, so it stays on our radar!

**Comment by adamdoe** [comment]
@eddt ,

Just discovered that this can be implemented easily using Mikado. When using the actual 'get_sidebar()' function Mikado has a widget called sticky sidebar. By simply adding this to the top of the widgets the sticky sidebar works! Adding this here for documentation.

**Comment by eddt** [comment]
Great find!
