### ISSUE TITLE
Subsites

### ISSUE THREAD

**Issue by adamdoe** [marketingincolor/egw-site-themes#84]
It might make sense to move our /help and /team knowledge bases into the theme. Doing this we could keep the same look and feel of myevergreenwellness.com and we would be able to manage the bases on the same site.

**Comment by eddt** [comment]
Yes, I agree this worth discussing. However a better method may be to keep them installed where they are and to simply add the theme to their setup, or another version of the theme if necessary, such as "open-variant-child", though much of the DISCUSSION main theme probably won't be needed.
