### ISSUE TITLE
Show Admin Bar

### ISSUE THREAD

**Issue by adamdoe** [marketingincolor/egw-site-themes#91]
@eddt 

I pulled a user report today and while looking through the meta I noticed that some users have TRUE set for show_admin_bar. These users were not admins.

**Comment by eddt** [comment]
And to clarify, there were probably a LOT of them, correct? Not just one or two?

**Comment by eddt** [comment]
Digging deeper into user creation, it seems this value is set to TRUE by default in WordPress when a user is created.

However, it doesn't appear to typically be the method that is employed to actually display the admin bar when the user is logged in. 

In fact, FarShore inserted this snippet into the functions.php file which controls who can actually see the admin bar on the FRONT of the site:

`if ((current_user_can('administrator') && is_admin()) || (is_super_admin())) {
    show_admin_bar(true);
} else {
    show_admin_bar(false);
}`

So, while they probably shouldn't TECHNICALLY be set to TRUE, I don't think its having any adverse or improper effect on the users or the site.

BUT - saying that - WAY TO KEEP YOUR EYES PEELED! @adamdoe
